// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetPublicIP() {
  return window['go']['main']['App']['GetPublicIP']();
}

export function GetTrafficStats() {
  return window['go']['main']['App']['GetTrafficStats']();
}

export function GetVPNInfo() {
  return window['go']['main']['App']['GetVPNInfo']();
}

export function ImportProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportProfile'](arg1, arg2, arg3, arg4);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function PickOvpnFile() {
  return window['go']['main']['App']['PickOvpnFile']();
}

export function UpdateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4);
}
