// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckChangelog() {
  return window['go']['main']['App']['CheckChangelog']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckProfileCerts() {
  return window['go']['main']['App']['CheckProfileCerts']();
}

export function ClearAuditLog() {
  return window['go']['main']['App']['ClearAuditLog']();
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetCertInfo(arg1) {
  return window['go']['main']['App']['GetCertInfo'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetPublicIP() {
  return window['go']['main']['App']['GetPublicIP']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTrafficStats() {
  return window['go']['main']['App']['GetTrafficStats']();
}

export function GetVPNInfo() {
  return window['go']['main']['App']['GetVPNInfo']();
}

export function ImportProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportProfile'](arg1, arg2, arg3, arg4);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function LoadAuditLog() {
  return window['go']['main']['App']['LoadAuditLog']();
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function PickOvpnFile() {
  return window['go']['main']['App']['PickOvpnFile']();
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function RunSpeedTest() {
  return window['go']['main']['App']['RunSpeedTest']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4);
}
