// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetPublicIP():Promise<string>;

export function GetTrafficStats():Promise<main.TrafficStats>;

export function GetVPNInfo():Promise<main.VPNInfo>;

export function ImportProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Profile>;

export function IsConnected():Promise<boolean>;

export function LoadProfiles():Promise<Array<main.Profile>>;

export function PickOvpnFile():Promise<string>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
